/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./../components/base/Badge.vue')['default']
    Button: typeof import('./../components/base/Button.vue')['default']
    Card: typeof import('./../components/base/Card.vue')['default']
    Drawer: typeof import('./../components/base/Drawer.vue')['default']
    FeaturedRoutes: typeof import('./../components/home/FeaturedRoutes.vue')['default']
    FilterPanel: typeof import('./../components/routes/FilterPanel.vue')['default']
    Footer: typeof import('./../components/layout/Footer.vue')['default']
    Header: typeof import('./../components/layout/Header.vue')['default']
    HeroSection: typeof import('./../components/home/HeroSection.vue')['default']
    InquiryModal: typeof import('./../components/inquiry/InquiryModal.vue')['default']
    Modal: typeof import('./../components/base/Modal.vue')['default']
    NavLink: typeof import('./../components/layout/NavLink.vue')['default']
    PromoCard: typeof import('./../components/promos/PromoCard.vue')['default']
    PromoSection: typeof import('./../components/home/PromoSection.vue')['default']
    RouteCard: typeof import('./../components/routes/RouteCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./../components/search/SearchBox.vue')['default']
    Skeleton: typeof import('./../components/base/Skeleton.vue')['default']
    Toast: typeof import('./../components/base/Toast.vue')['default']
    USPSection: typeof import('./../components/home/USPSection.vue')['default']
  }
}
